"""
seed_database.py - Database Seeding for Land Acquisition Platform
=================================================================
Populates the SQLAlchemy Project table from CSV data generated by ML pipeline.
Requirements:
  - Idempotent (safe to run multiple times)
  - Uses project_id as unique key (never duplicates, updates on conflict)
  - Reads ml/ongoing_projects.csv and populates all 13 prediction-time fields
  - Preserves actual_delay_days as NULL for ongoing projects
  - Preserves intervention fields as NULL/empty
  - On empty DB, also seeds ml/land_data.csv so full historical dataset is available
"""

import os
import sys
import numpy as np
import pandas as pd

# Ensure backend directory is on sys.path
BACKEND_DIR = os.path.abspath(os.path.dirname(__file__))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from app.database import Base, engine, SessionLocal, Project

# District center coordinates for geospatial mapping
DISTRICT_COORDS = {
    "Mumbai":     {"lat": 19.0760, "lon": 72.8777},
    "Pune":       {"lat": 18.5204, "lon": 73.8567},
    "Nagpur":     {"lat": 21.1458, "lon": 79.0882},
    "Nashik":     {"lat": 19.9975, "lon": 73.7898},
    "Aurangabad": {"lat": 19.8762, "lon": 75.3433},
}


def _seed_dataframe(session, df: pd.DataFrame, is_ongoing: bool = False) -> int:
    """Seed or update projects from a DataFrame idempotently."""
    np.random.seed(42)
    count = 0

    for _, row in df.iterrows():
        pid = int(row["project_id"])
        proj = session.query(Project).filter(Project.project_id == pid).first()
        if not proj:
            proj = Project(project_id=pid)
            session.add(proj)

        # Populate 13 prediction-time fields + identifiers
        proj.project_name = str(row["project_name"])
        proj.district = str(row["district"])
        proj.project_type = str(row["project_type"])
        proj.total_acres = float(row["total_acres"])
        proj.land_acquired_pct = float(row["land_acquired_pct"])
        proj.approval_days_pending = int(row["approval_days_pending"])
        proj.compensation_disbursed_pct = float(row["compensation_disbursed_pct"])
        proj.legal_cases_count = int(row["legal_cases_count"])
        proj.ownership_disputes = int(row["ownership_disputes"])
        proj.rnp_progress_pct = float(row["rnp_progress_pct"])
        proj.possession_pct = float(row["possession_pct"])
        proj.affected_families = int(row["affected_families"])
        proj.doc_deficiency_score = float(row["doc_deficiency_score"])
        proj.historical_district_delay_avg = float(row["historical_district_delay_avg"])

        if is_ongoing:
            # Contract: actual_delay_days is NULL, intervention fields empty/NULL
            proj.actual_delay_days = None
            proj.intervention_taken = None
            proj.intervention_date = None
        else:
            if "actual_delay_days" in row and pd.notna(row["actual_delay_days"]):
                proj.actual_delay_days = int(row["actual_delay_days"])
            if "intervention_taken" in row and pd.notna(row["intervention_taken"]):
                proj.intervention_taken = str(row["intervention_taken"]) if str(row["intervention_taken"]).strip() else None

        if "delay_label" in row and pd.notna(row["delay_label"]):
            proj.delay_label = int(row["delay_label"])

        # Jitter coordinates for GIS map if not already assigned
        if proj.lat is None or proj.lon is None:
            center = DISTRICT_COORDS.get(proj.district, {"lat": 19.0, "lon": 73.0})
            proj.lat = round(center["lat"] + float(np.random.uniform(-0.15, 0.15)), 6)
            proj.lon = round(center["lon"] + float(np.random.uniform(-0.15, 0.15)), 6)

        count += 1

    return count


def seed_projects(ongoing_csv_path: str = None, historical_csv_path: str = None) -> dict:
    """
    Main database seeding routine.
    Creates tables if necessary.
    Seeds ongoing projects from ongoing_projects.csv.
    If database has no projects, seeds land_data.csv first.
    """
    ml_dir = os.path.abspath(os.path.join(BACKEND_DIR, "..", "ml"))
    if ongoing_csv_path is None:
        ongoing_csv_path = os.path.join(ml_dir, "ongoing_projects.csv")
    if historical_csv_path is None:
        historical_csv_path = os.path.join(ml_dir, "land_data.csv")

    # 1. Create tables if not present
    Base.metadata.create_all(bind=engine)

    session = SessionLocal()
    results = {"historical_seeded": 0, "ongoing_seeded": 0}

    try:
        current_count = session.query(Project).count()

        # 2. Seed historical data if table is completely empty
        if current_count == 0 and os.path.exists(historical_csv_path):
            print(f"[seed_database] Database is empty. Seeding historical data from {historical_csv_path}...", flush=True)
            df_hist = pd.read_csv(historical_csv_path)
            hist_count = _seed_dataframe(session, df_hist, is_ongoing=False)
            session.commit()
            results["historical_seeded"] = hist_count
            print(f"[seed_database] Seeded {hist_count} historical projects.", flush=True)

        # 3. Seed/update ongoing projects
        if os.path.exists(ongoing_csv_path):
            print(f"[seed_database] Seeding ongoing projects from {ongoing_csv_path}...", flush=True)
            df_ongoing = pd.read_csv(ongoing_csv_path)
            ongoing_count = _seed_dataframe(session, df_ongoing, is_ongoing=True)
            session.commit()
            results["ongoing_seeded"] = ongoing_count
            print(f"[seed_database] Successfully seeded/updated {ongoing_count} ongoing projects.", flush=True)
        else:
            print(f"[seed_database] Warning: Ongoing projects file not found at {ongoing_csv_path}", flush=True)

        total_projects = session.query(Project).count()
        results["total_projects"] = total_projects
        print(f"[seed_database] Database seeding complete. Total projects in DB: {total_projects}", flush=True)
        return results

    except Exception as e:
        session.rollback()
        print(f"[seed_database] Error during seeding: {e}", flush=True)
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed_projects()
